version: '3.8'

services:
  app_prod:
    container_name: app_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod_im
    image: app_prod
    ports:
      - "5001:5001"
      - "5173:5173"
      - "80:5001"
    volumes:
      - .:/app
    depends_on:
      - pgsql
    command: "npm run start"
    mem_limit: 512m
    cpus: 0.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    profiles:
      - "prod"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@pgsql:5432/stl
    env_file:
      - .env
  aws_prod:
    container_name: app_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod_im
    image: app_prod
    ports:
      - "5001:5001"
      - "5173:5173"
      - "80:5001"
    volumes:
      - .:/app
    command: "npm run start"
    mem_limit: 512m
    cpus: 0.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    profiles:
      - "prod"
    environment:
      - DATABASE_URL=postgres://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/stl
      - echo "DATABASE_URL"
    env_file:
      - .env
   
  app_dev:
    container_name: app_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev_im
    image: app_dev
    ports:
      - "5001:5001"
      - "5173:5173"
    volumes:
      - .:/app
    depends_on:
      - pgsql
    command: "npm run dev"
    mem_limit: 512m
    cpus: 1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    environment:
      - DATABASE_URL=postgres://postgres:postgres@pgsql:5432/stl
    env_file:
      - .env
    profiles:
      - ""

      

  pgsql:
    container_name: pgsql
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stl
    volumes:
      - ./data:/var/lib/postgresql/data


      


  
